/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 home.gltf 
Author: Nicolai Kilstrup (https://sketchfab.com/nkilstrup)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/kitchen-furniture-ebc5742566c1443183790d43f1b3e324
Title: Kitchen Furniture
*/

import React, { useRef,useEffect, useLayoutEffect } from 'react'
import { useGLTF,useScroll } from '@react-three/drei'
import {useFrame} from '@react-three/fiber'
import gsap from 'gsap'

const HEIGHT_MAHESH=5
const WIDTH=2
export default function Home1(props) {
  const { nodes, materials } = useGLTF('./home.gltf')
  const ref = useRef()
  const t1=useRef();
const scroll=useScroll();
useFrame(()=>{
  t1.current.seek(scroll * t1.current.duration);
});

  
  useLayoutEffect(()=>{
    t1.current=gsap.timeline();
    t1.current.to(
      ref.current.position,{
        duration:2,
        y:-HEIGHT_MAHESH*(WIDTH-1),

      },
      0
    )

  },[]);
  console.log("Inside function")
  

  return (
    <group ref={ref} {...props} dispose={null}>
      <group position={[1, 0, 0.5]} >
        <mesh geometry={nodes.Object_16.geometry} material={materials.Carpet_A} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.Carpet_A_Ends} />
      </group>
      <group position={[0.7, 1, -2.4]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.5}>
        <mesh geometry={nodes.Object_19.geometry} material={materials.Trims_Painted_A} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.Glass_Cupboard_A} />
      </group>
      <group position={[-1, 1, -2]} scale={0.857}>
        <mesh geometry={nodes.Object_22.geometry} material={materials.Trims_Painted_A} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.Glass_Cupboard_A} />
      </group>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Radiators} position={[-1.5, 0, 0.5]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.Radiators} position={[-0.5, 0, 0.5]} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.Table_Kitchen_A} position={[-1.5, 0, -0.5]} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.Chairs_A} position={[1, 0, -0.5]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.Chairs_A} position={[0, 0, -0.5]} rotation={[0, -Math.PI / 2, 0]} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.Chairs_A} position={[2, 0, -0.5]} scale={1.252} />
    </group>
  )
}

useGLTF.preload('/home.gltf')
